services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    volumes:
      - ./cache:/cache:z
      - ./config:/config:z
      - /root/media/EC:/media/videos:ro
      - ./JellyfinJav/bin/Debug/net9.0/JellyfinJav.dll:/config/plugins/JellyfinJav/JellyfinJav.dll:ro
      - ~/.nuget/packages/anglesharp/1.1.2/lib/netstandard2.0/AngleSharp.dll:/config/plugins/JellyfinJav/AngleSharp.dll:ro
    ports:
      - 8896:8096
